apiVersion: v1
kind: AdminCluster | UserCluster
metadata:
  name: shared-infra-cluster-01
spec:
  nodePools:
  - name: shared-infa-nodepool-01
    replicas: 3
    osImageType: cos
  autoscaling:
    minReplicas: 1
    maxReplicas: 5
  secretsEncryption:
    mode: GeneratedKey
    generatedKey:
      keyVersion: 1
  